-- Create announcements table with semester and section scoping
CREATE TABLE IF NOT EXISTS public.announcements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    name text NOT NULL,
    title text NOT NULL,
    announcement text NOT NULL,
    subject text,
    type text DEFAULT 'general' NOT NULL,
    date_override date,
    subject_override text,
    semester text,
    section text
);

-- Migration query if announcements table already exists:
ALTER TABLE public.announcements ADD COLUMN IF NOT EXISTS semester text;
ALTER TABLE public.announcements ADD COLUMN IF NOT EXISTS section text;

-- Enable Realtime for announcements
ALTER PUBLICATION supabase_realtime ADD TABLE public.announcements;

-- Create device_tokens table to store FCM registration tokens with section scoping
CREATE TABLE IF NOT EXISTS public.device_tokens (
    token text PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    platform text NOT NULL,
    semester text,
    section text
);

-- Migration query if device_tokens table already exists:
ALTER TABLE public.device_tokens ADD COLUMN IF NOT EXISTS semester text;
ALTER TABLE public.device_tokens ADD COLUMN IF NOT EXISTS section text;

-- Create teacher_names table to store crowdsourced faculty full names and moderation status
CREATE TABLE IF NOT EXISTS public.teacher_names (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_code text NOT NULL,
    full_name text NOT NULL,
    status text DEFAULT 'pending' NOT NULL, -- 'pending', 'approved', 'rejected'
    submitted_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    reviewed_at timestamp with time zone
);

-- Enable Realtime for teacher_names
ALTER TABLE PUBLICATION supabase_realtime ADD TABLE public.teacher_names;

