-- Create announcements table
CREATE TABLE IF NOT EXISTS public.announcements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    name text NOT NULL,
    title text NOT NULL,
    announcement text NOT NULL,
    subject text,
    type text DEFAULT 'general' NOT NULL,
    date_override date,
    subject_override text
);

-- Enable Realtime for announcements (Optional, but useful)
ALTER PUBLICATION supabase_realtime ADD TABLE public.announcements;

-- Create device_tokens table to store FCM registration tokens
CREATE TABLE IF NOT EXISTS public.device_tokens (
    token text PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    platform text NOT NULL
);
